# Generated by Django 4.2.6 on 2023-11-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ladiesclothing_mensneakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladiesclothing',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mensneakers',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mentop',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
